[general]
import = ["/home/satoru/.config/alacritty/dracula.toml"]

[font]
size = 18.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
decorations = "full"

[window.dimensions]
columns = 86
lines = 28

[window.padding]
x = 7
y = 7

