# [general]
import = ["~/.config/alacritty/dracula.toml"]
# import = ["~/.config/alacritty/gruvbox.toml"]

[window]
decorations = "none"
dimensions = { columns = 92, lines = 28 }
padding = { x = 5, y = 5 }
dynamic_padding = true


[font]
size = 18

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Propo"
style = "Regular"

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>	'''

